### ISSUE TITLE
1.15 Paper startup error

### ISSUE THREAD

**Issue by leasoncre** [Buam/ultimatesigns#1]
Startup error, plugin does not load. :(
Java 8x64, Paper Spigot 1.15.1

`[11:44:04] [Server thread/INFO]: [UltimateSigns] Enabling UltimateSigns v1.6.0
[11:44:04] [Server thread/INFO]: [UltimateSigns] No Vault dependency found!
[11:44:04] [Server thread/INFO]: [UltimateSigns] failed to create messages.yml
[11:44:04] [Server thread/INFO]: [UltimateSigns] failed to create aliases.yml
[11:44:04] [Server thread/ERROR]: Error occurred while enabling UltimateSigns v1.6.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.buam.ultimatesigns.SignManager.loadSigns(SignManager.java:201) ~[?:?]
	at com.buam.ultimatesigns.SignManager.<init>(SignManager.java:59) ~[?:?]
	at com.buam.ultimatesigns.UltimateSigns.onEnable(UltimateSigns.java:121) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:44:04] [Server thread/INFO]: [UltimateSigns] Disabling UltimateSigns v1.6.0`

**Comment by Buam** [comment]
Thanks for opening this issue. I am not able to reproduce this error.
I would recommend you to try a newer Java version if that's possible.

**Comment by leasoncre** [comment]
Oh, i just noticed the problem. Which i fixed a few days ago, though unrelated.
`No Vault dependency found!` derps.. 
PS. Vault Dependancy not listed on Plugin webpage.
